import { z } from "zod";

/**
 * Strict Zod validation schema for synthesized React components.
 * Forces the probabilistic string output from an LLM to prove it matches
 * modern Next.js and TailwindCSS architectural patterns before saving.
 */
export const synthesizedComponentSchema = z.object({
  componentName: z
    .string()
    .min(1, "Component name label tracking is mandatory.")
    .regex(
      /^[A-Z][a-zA-Z0-9]*$/,
      "Component name must follow strict React PascalCase conventions.",
    ),

  targetTargetFolder: z.string().min(1),

  // The raw code string block generated by the model
  generatedCode: z
    .string()
    .min(1, "Generated code canvas cannot be an empty string.")
    // Refinement 1: Verify native React import primitives are present
    .refine((code) => code.includes("import") && code.includes("react"), {
      message:
        "Architectural Violation: Generated code lacks modern modular import declarations.",
    })
    // Refinement 2: Actively block legacy server-side scripting tags from leaking through
    .refine((code) => !code.includes("<cf") && !code.includes("</cf"), {
      message:
        "Security Breach: Legacy ColdFusion tags leaked through synthesis layers into the modern codebase.",
    })
    // Refinement 3: Enforce strict use of Tailwind utility styles over archaic properties
    .refine((code) => !code.includes("bgcolor=") && !code.includes("<font"), {
      message:
        "Style Compliance Violation: Archaic presentational attributes detected. Code must utilize pure Tailwind CSS tokens.",
    }),

  // Track dependencies the agent claims it utilized
  usedDependencies: z
    .array(z.string())
    .describe(
      "List of internal or external library hooks used (e.g., lucide-react, client-state hooks).",
    ),
});

export type SynthesizedComponent = z.infer<typeof synthesizedComponentSchema>;
